syntax = "proto3";

package richter.v1;

import "buf/validate/validate.proto";
import "richter/v1/users.proto";

message LoginRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string password = 2 [(buf.validate.field).string.min_len = 8];
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
  int64 expires_in = 3;
  User user = 4;
}

message RefreshTokenRequest {
  string refresh_token = 1 [(buf.validate.field).string.min_len = 1];
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  int64 expires_in = 3;
}

message LogoutRequest {
  string refresh_token = 1 [(buf.validate.field).string.min_len = 1];
}

message LogoutResponse {}

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
  rpc Logout(LogoutRequest) returns (LogoutResponse) {}
}
